In [1]:
import pandas as pd
import numpy as np
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
import os
from mpl_toolkits.mplot3d import Axes3D
from sklearn import naive_bayes as nb
from sklearn.cross_validation import train_test_split

In [2]:
raw = pd.read_csv('MicrosoftGestureDataset-RC/data/P1_1_12A_p21.csv',sep=' ',header=None)
raw=raw.drop(xrange(0,20),axis=0).drop(0,axis=1).drop((xrange(4,80,4)),axis=1).drop(80,axis=1)

In [3]:
column_names=['hip_center_x','hip_center_y','hip_center_z',
              'spine_x','spine_y','spine_z','shoulder_center_x',
              'shoulder_center_y','shoulder_center_z','head_x',
              'head_y','head_z','shoulder_left_x','shoulder_left_y',
             'shoulder_left_z','elbow_left_x','elbow_left_y','elbow_left_z',
             'wrist_left_x','wrist_left_y','wrist_left_z','hand_left_x',
              'hand_left_y','wrist_left_z','shoulder_right_x','shoulder_right_y',
             'shoulder_right_z','elbow_right_x','elbow_right_y','elbow_right_z',
             'wrist_right_x','wrist_right_y','wrist_right_z','hand_right_x',
             'hand_right_y','hand_right_z','hip_left_x','hip_left_y','hip_left_z',
             'knee_left_x','knee_left_y','knee_left_z','ankle_left_x','ankle_left_y',
             'ankle_left_z','foot_left_x','foot_left_y','foot_left_z','hip_right_x',
             'hip_right_y','hip_right_z','knee_right_x','knee_right_y','knee_right_z',
             'ankle_right_x','ankle_right_y','ankle_right_z','foot_right_x','foot_right_y',
             'foot_right_z']

raw.columns=column_names
len(column_names)

60

In [4]:
len(raw.columns)


60

In [5]:
# create DataFrame for each axis of each joint
# A BAD IDEA
# for i in column_names:
#     print i
#     exec('{} = pd.DataFrame([1,2,3,4])'.format(i))
# A BETTER IDEA
joints = {k: pd.DataFrame([]) for k in raw.columns }


In [94]:
gestures = pd.DataFrame()
labels = pd.Series()
labels_array=[]
sizes = [1];
i=0
for root, dirs, files in os.walk("MicrosoftGestureDataset-RC/data"):
        for f in files:
            if f.endswith(".csv"):
                temp = pd.read_csv(os.path.join(root,f),sep=' ',header=None).drop(xrange(0,20),axis=0).drop(0,axis=1).drop((xrange(4,80,4)),axis=1).drop(80,axis=1)
                temp
                temp.columns=column_names
                for joint_name in temp.columns:
                    joints[joint_name] = joints[joint_name].append(temp[joint_name])
                labels_array.append(f[f.find('_',3)+1:f.rfind('_')].replace('A',''))
                sizes.append(len(temp))
                print f[f.find('_',3)+1:f.rfind('_')].replace('A','');
                i=i+1;
                if i>100:
                    break;
print str(i)+" gesture files loaded"

gestures

10
10
10
10
10
11
11
11
11
11
12
12
12
12
12
12
12
12
12
12
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
7
7
7
7
7
7
7
7
7
7
8
8
8
8
8
8
8
8
8
8
9
9
9
9
9
9
9
9
9
9
10
101 gesture files loaded


Empty DataFrame
Columns: []
Index: []

In [95]:
classifiers = {k: nb.GaussianNB() for k in raw.columns }

In [97]:
# training/test set split
training_sets = {}
test_sets = {}
for c in classifiers:
    train, test = train_test_split(joints[c], test_size = 0.2);
#     training_sets[c]=train.dropna(axis=1,how='any');
#     test_sets[c]=test.dropna(axis=1,how='any');
    training_sets[c]=train.dropna(axis=1,how='any');
    test_sets[c]=test.dropna(axis=1,how='any');
    

In [121]:
pd.Series(labels_array[:50]).value_counts()

1     10
3     10
12    10
2     10
10     5
11     5
dtype: int64

In [99]:
i = 0
for c in classifiers:
    try:
        classifiers[c] = classifiers[c].fit(training_sets[c].T[:50],labels_array[:len(training_sets[c][:50])])
        print classifiers[c].class_prior_
        print 'classifier #'+str(i)+' trained'
        
    except ValueError as e:
        print(e)
    i=i+1

[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #0 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #1 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #2 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #3 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #4 trained
Found arrays with inconsistent numbers of samples: [ 2 50]
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #6 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #7 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #8 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #9 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #10 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #11 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #12 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #13 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #14 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #15 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #16 trained
[ 0.2  0.1  0.1  0.2  0.2  0.2]
classifier #17 trained
[ 0.2  0.1  0.1

In [100]:
joints['ankle_left_x']=joints['ankle_left_x'].dropna(axis=1,how='any')


In [101]:
joints['ankle_left_x'][:101]

20        21        22        23        24        25   \
ankle_left_x -0.088440 -0.088358 -0.088128 -0.087376 -0.087528 -0.087150   
ankle_left_x -0.193481 -0.193312 -0.194001 -0.193475 -0.193391 -0.193195   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.104492 -0.104582 -0.108029 -0.108818 -0.108684 -0.108939   
ankle_left_x -0.101685 -0.101586 -0.101697 -0.101696 -0.101441 -0.114005   
ankle_left_x -0.188232 -0.188595 -0.189755 -0.189747 -0.190553 -0.191007   
ankle_left_x -0.278564 -0.277647 -0.277489 -0.279021 -0.276246 -0.276867   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.139160 -0.136949 -0.135158 -0.134870 -0.134690 -0.134750   
ankle_left_x -0.068115 -0.067983 -0.067989 -0.067953 -0.067994 -0.067975   
ankle_left_x  0.000000  0.000000  0.000000 -0.123535 -0.124738 -0.123043   
ankle_left_x -0.353516 -0.352297 -0.352418 -0.352598 -0.352332 -0.351992   
ankle_left_x -0.573242 -0.570970 -0.571112 -0.571252 -0.571427 -0.567081   
ankle_left_x -0.146973 -0.147003 -0.146918 -0.146962 -0.148364 -0.148575   
ankle_left_x -0.000678 -0.000883 -0.001383 -0.001191 -0.000963  0.001369   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.389160 -0.388538 -0.389959 -0.392026 -0.390023 -0.386039   
ankle_left_x  0.000000  0.000000  0.000000 -0.428046 -0.435243 -0.440286   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.076172 -0.074966 -0.073073 -0.072437 -0.073892 -0.074465   
ankle_left_x -0.085754 -0.085602 -0.085319 -0.085345 -0.085503 -0.086756   
ankle_left_x -0.360352 -0.360561 -0.362999 -0.363786 -0.363805 -0.363611   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.091553 -0.092086 -0.092305 -0.092301 -0.092750 -0.092335   
ankle_left_x -0.068420 -0.067836 -0.067354 -0.063898 -0.062398 -0.060979   
ankle_left_x -0.115540 -0.115243 -0.116441 -0.116494 -0.116916 -0.117665   
ankle_left_x -0.325684 -0.326439 -0.327641 -0.327665 -0.328110 -0.327729   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.087219 -0.085943 -0.084596 -0.084177 -0.081706 -0.081945   
...                ...       ...       ...       ...       ...       ...   
ankle_left_x -0.107849 -0.106207 -0.105407 -0.104913 -0.105284 -0.106540   
ankle_left_x  0.000000 -0.340820 -0.340531 -0.340403 -0.339285 -0.338811   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.058379 -0.064315 -0.064124 -0.064140 -0.064017 -0.064099   
ankle_left_x  0.006210  0.005575  0.005479  0.005456  0.005503  0.005500   
ankle_left_x -0.146484 -0.146295 -0.146041 -0.146215 -0.146258 -0.146867   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x  0.000000 -0.432373 -0.432735 -0.432624 -0.432526 -0.432498   
ankle_left_x -0.102661 -0.102584 -0.102964 -0.103148 -0.101983 -0.102379   
ankle_left_x -0.006954 -0.009650 -0.010370 -0.009264 -0.010562 -0.010295   
ankle_left_x -0.164795 -0.165617 -0.172903 -0.174220 -0.176077 -0.179842   
ankle_left_x  0.000000 -0.323486 -0.324937 -0.325139 -0.325326 -0.326262   
ankle_left_x -0.509277 -0.509335 -0.508859 -0.508952 -0.507828 -0.507276   
ankle_left_x -0.078674 -0.078635 -0.079093 -0.078592 -0.078812 -0.078810   
ankle_left_x -0.097412 -0.090372 -0.086338 -0.085249 -0.084889 -0.084169   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.417480 -0.417217 -0.415971 -0.414186 -0.412359 -0.411935   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
ankle_left_x -0.025345 -0.028192 -0.032301 -0.033188 -0.042226 -0.035126   
ankle_left_x -0.172729 -0.172681 -0.172762 -0.173330 -0.173061 -0.1

In [102]:
joints['ankle_left_x'].shape

(1831, 519)

In [109]:
len(labels_array)

101

In [111]:
pd.Series(labels_array).unique()

array(['10', '11', '12', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype=object)

In [104]:
classifier = nb.GaussianNB()
classifier.fit(joints['ankle_left_x'][:101],labels_array[:len(joints['ankle_left_x'])])

GaussianNB()

In [105]:
test_sets['ankle_left_x'][:20].shape

(20, 519)

In [112]:
results = classifier.predict(training_sets['ankle_left_x'].dropna(axis=1,how='any'))

In [116]:
pd.Series(results).value_counts()

1     696
11    247
5     171
12    166
10     99
8      71
2      10
3       2
4       2
dtype: int64